[extend]
useDefault = true

[[rules]]
id = "generic-api-key"
entropy = 2

[[allowlists]]
description = "Ignore README"
paths = [
    "README.md"
]

[[allowlists]]
description = "Ignore .secret"
paths = [
    ".secret"
]
